### ISSUE TITLE
JavaScript error occured in the main process

### ISSUE THREAD

**Issue by Chillthebone** [Jiiks/BetterDiscordApp#107]
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
SyntaxError: Unexpected token <
    at Object.parse (native)
    at BetterDiscord.parseEmoteData (C:\Users\Joey\AppData\Local\Discord\app-0.0.283\resources\node_modules\betterdiscord\lib\BetterDiscord.js:501:30)
    at C:\Users\Joey\AppData\Local\Discord\app-0.0.283\resources\node_modules\betterdiscord\lib\BetterDiscord.js:466:53
    at IncomingMessage.<anonymous> (C:\Users\Joey\AppData\Local\Discord\app-0.0.283\resources\node_modules\betterdiscord\lib\utils.js:52:13)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

[OK]

Getting this as I try to launch Discord. The installation went fine, 0 errors. Tried debugging both the installer and the Discord.exe and it doesn't seem to do anything

**Comment by Chillthebone** [comment]
The reason would be a missing emotes_twitch_subscriber.json file in the BetterDiscord folder. 

https://up1.ca/#3-Oug8ZY0fXHiUmR6YCPfQ

Here's a link to anyone who stumbles upon this. Happy holidays.

**Comment by DoNotSpamPls** [comment]
*Added fix in the FAQ in the wiki, just to know*

**Comment by Pand3m0nia** [comment]
Hi there,

I've just started using Discord and tried to install BetterDiscord. I get the same error as above. I've tried both solutions mentioned in the FAQ, i.e. downloading and adding the missing file as well as deleting all files from the BetterDiscord folder. I've tried uninstalling and reinstalling both Discord and BetterDiscord to no avail. 

I don't know if this is relevant, but on my laptop the BetterDiscord folder is within Discord-->app-0.0.283-->resources-->node-modules-->BetterDiscord. Have I installed it in the right place?

Please help.

Thanks
