### ISSUE TITLE
Not working with PTB (Mac)

### ISSUE THREAD

**Issue by mkody** [Jiiks/BetterDiscordApp#152]
I've changed the path in `index.js` to point to the Discord PTB release, and... Well, nothing seems to load.
Except when I tried to connect a Twitch account. Everytime I lose focus on Discord, I get an error.
The first time:
```
Uncaught Exception:
TypeError: _betterDiscord.BetterDiscord is not a function
    at BrowserWindow.<anonymous> (/Applications/Discord PTB.app/Contents/Resources/app/app/index.js:502:18)
    at emitOne (events.js:82:20)
    at BrowserWindow.emit (events.js:169:7)
```

The second time:
```
Uncaught Exception:
TypeError: _betterDiscord.BetterDiscord is not a function
    at BrowserWindow.<anonymous> (/Applications/Discord PTB.app/Contents/Resources/app/app/index.js:502:18)
    at emitOne (events.js:82:20)
    at BrowserWindow.emit (events.js:169:7)
    at Object.module.exports.showErrorBox (/Applications/Discord PTB.app/Contents/Resources/atom.asar/browser/api/lib/dialog.js:159:35)
    at process.<anonymous> (/Applications/Discord PTB.app/Contents/Resources/atom.asar/browser/lib/init.js:57:30)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:223:26)
```

And third time and so on...
```
Uncaught Exception:
TypeError: _betterDiscord.BetterDiscord is not a function
    at BrowserWindow.<anonymous> (/Applications/Discord PTB.app/Contents/Resources/app/app/index.js:502:18)
    at emitOne (events.js:82:20)
    at BrowserWindow.emit (events.js:169:7)
    at Object.module.exports.showErrorBox (/Applications/Discord PTB.app/Contents/Resources/atom.asar/browser/api/lib/dialog.js:159:35)
    at process.<anonymous> (/Applications/Discord PTB.app/Contents/Resources/atom.asar/browser/lib/init.js:57:30)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:223:26)
    at Object.module.exports.showErrorBox (/Applications/Discord PTB.app/Contents/Resources/atom.asar/browser/api/lib/dialog.js:159:35)
    at process.<anonymous> (/Applications/Discord PTB.app/Contents/Resources/atom.asar/browser/lib/init.js:57:30)
```

**Comment by AraHaan** [comment]
It does not work for Widnows PTB either. Maybe Jiiks Can fix it. I did just send a PR for the Installer for Windows that fixes a few issues (tested with VS2015).

**Comment by Jiiks** [comment]
I don't provide support for PTB
