### ISSUE TITLE
Install Update Error (Mac)

### ISSUE THREAD

**Issue by Syconawt** [Jiiks/BetterDiscordApp#209]
Hi there,

I'm trying to install BD0.2.6 on Mac and I keep running into the following syntax error (sensitive info removed):

```
/Users/<USERNAME>/Downloads/BD0.2.6OSX/index.js:115
 fs.exists(process.env.HOME + _prefsPath + emotes_twitch_global, (exists) => {
                                                                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

```

Any ideas on how to fix it? Thanks.

**Comment by iVEnoVaLue** [comment]
You don't have the last version of nodejs.
