### ISSUE TITLE
Cannot find 'asar' module OSX

### ISSUE THREAD

**Issue by Gymnophoria** [Jiiks/BetterDiscordApp#321]
Hello, I was trying to install this with install.sh on Terminal, yet it keeps coming up with "Error: Cannot find module 'asar'"
Asar is quite obviously there, under the node_modules folder. Here is the error message:

```
Name-iMac:~ Name$ /Users/Name/Downloads/BD0.2.8OSX-2/install.sh ; exit;
module.js:327
    throw err;
    ^

Error: Cannot find module 'asar'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/Name/index.js:7:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.


[Process completed]
```

Using an iMac (Mid-2011) with default specs.

Thanks in advance :P

**Comment by kurisubrooks** [comment]
What happens if you `cd betterdiscord && node index.js` from the command line instead of executing the bash file?

**Comment by mattbox** [comment]
That should work. The install.sh script just runs `node index.js` without changing the directory first.
