### ISSUE TITLE
V2 Not working with canary 0.0.32

### ISSUE THREAD

**Issue by ghost** [Jiiks/BetterDiscordApp#535]
I tried the v2 branch cause normal BD stopped working for me on canary.

![image](https://user-images.githubusercontent.com/16898876/28476633-f43bde4e-6e50-11e7-98d5-3e70bfb60707.png)

![image](https://user-images.githubusercontent.com/16898876/28476639-fa92d270-6e50-11e7-9a14-3b9f831f9054.png)

![image](https://user-images.githubusercontent.com/16898876/28476650-0709303a-6e51-11e7-83b1-52099618f6e3.png)

**Comment by SexyGithubber** [comment]
Is there any way to see which utils.js caused the initial error?

**Comment by ibrokemypie** [comment]
```
Uncaught Exception:
TypeError: Cannot read property 'webContents' of undefined
    at Timeout.BdInjector.setInterval [as _onTimeout] (/Applications/Discord PTB.app/Contents/Resources/app.asar/index.js:31:31)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```


```
Uncaught Exception:
TypeError: Cannot read property 'webContents' of undefined
    at Timeout.BdInjector.setInterval [as _onTimeout] (/Applications/Discord PTB.app/Contents/Resources/app/index.js:31:31)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
    at listOnTimeoutNT (timers.js:255:26)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
