### ISSUE TITLE
Running installer from a different drive than the installation of Discord causes crash

### ISSUE THREAD

**Issue by 10se1ucgo** [Jiiks/BetterDiscordApp#567]
An unhandled System.IO.IOException is raised when `Moving BetterDiscord into resources\node_modules\`

```
System.IO.IOException occurred
  HResult=0x80131620
  Message=Source and destination path must have identical roots. Move will not work across volumes.
  Source=mscorlib
  StackTrace:
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at BetterDiscordWI.panels.Panel2.<>c__DisplayClass7_0.<DeleteDirs>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

I'm not sure why that's not allowed. Consider using a Copy and Delete instead of a Move.

**Comment by Inve1951** [comment]
.net should handle this :thinking:

**Comment by 10se1ucgo** [comment]
[It's written in the docs.](https://msdn.microsoft.com/en-us/library/system.io.directory.move(v=vs.110).aspx?cs-save-lang=1&cs-lang=csharp#Anchor_1)

**Comment by 10se1ucgo** [comment]
nice

**Comment by Inve1951** [comment]
open a new ticket at https://github.com/rauenzi/BetterDiscordApp if BBD installer has the same issue
this repo is no longer maintained
