### ISSUE TITLE
Upon using the git version of betterdiscord :

### ISSUE THREAD

**Issue by HeraKumi** [Jiiks/BetterDiscordApp#628]
When I installed betterdiscord from this repo, it done broke my discord.

hera@server ~                                                                                                           [3:34:06] 
> $ discord                                                                                                                      
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module './utils'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/opt/discord/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/betterdiscord-git/lib/BetterDiscord.js:13:14)
    at Object.<anonymous> (/usr/lib/betterdiscord-git/lib/BetterDiscord.js:846:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

Linux distro: Arch Linux
discord version: Latest
betterdiscord Version: Git latest

**Comment by Inve1951** [comment]
rename Utils.js to lowercase
