### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Bluscream** [Jiiks/BetterDiscordApp#73]
![pic](http://puu.sh/lQLJL/8c01946a2d.png)

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Cannot find module 'C:\Users\Timo\AppData\Local\Discord\app-0.0.283\resources\app\app\index.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Object.<anonymous> (C:\Users\Timo\AppData\Local\Discord\app-0.0.283\resources\atom.asar\browser\lib\init.js:123:10)
    at Object.<anonymous> (C:\Users\Timo\AppData\Local\Discord\app-0.0.283\resources\atom.asar\browser\lib\init.js:125:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:129:18)

[OK]
```

**Comment by Jiiks** [comment]
Looks like you're missing some files. 
Run the installer again.

**Comment by Bluscream** [comment]
Yeah. The installer was crashing all the time so i debugged with VS and found out the line

``` cpp
Directory.Move(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + "\\BetterDiscord\\temp\\BetterDiscordApp-stable", GetParent().DiscordPath + "\\resources\\node_modules\\BetterDiscord");
```

was causing the issues. So i commented it out and it worked :+1

**Comment by Jiiks** [comment]
Interesting, did it fail to download the release? Anyhow good to hear you got it working :)
